export const ActionTypes = {
    SET_FANTASYBOOKS: "SET_FANTASYBOOKS",
    SET_MYSTERYBOOKS: "SET_MYSTERYBOOKS",
    SET_ROMANCEBOOKS: "SET_ROMANCEBOOKS",
    SET_YABOOKS: "SET_YABOOKS",
    SET_BIOBOOKS: "SET_BIOBOOKS",
    SELECTED_BOOK: "SELECTED_BOOK",
    REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",
    ADD_TO_TBR: "ADD_TO_TBR",
    REMOVE_FROM_TBR: "REMOVE_FROM_TBR",
    SET_SEARCH_INFO: "SET_SEARCH_INFO",
}